# Generated by Django 4.2.7 on 2025-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_remove_customuser_user_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('video', models.FileField(null=True, upload_to='video')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
